image: node:20

stages:
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm install

newman_tests:
  stage: test
  script:
    - npm install -g newman
    - newman run spotify-graphql-api.postman_collection.json -e production.postman_environment.json
  only:
    - branches
    - merge_requests
